### PR TITLE
small "refresh" for readme.md

### PR DESCRIPTION
**Pull request by tristann21**
A small "refresh" made for Williams-Console

Asked for in issue https://github.com/contrarybaton60/Williams-Console/issues/1

- Revamped the "features" tab to highlight prominent mods and provide links to their respective authors.
- Enhanced the content displayed in the "info" tab.
- Refined the messaging in the "help and support" and included a hyperlink to the issues page.
- Renamed the "Credits" tab to "Credits and Licensing."
- Reorganized the download headers to appear below the image.

Also added #saveminecraft in [line 25](https://github.com/contrarybaton60/Williams-Console/pull/8/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R25) with a YouTube hyperlink explaining it in detail. If you want that removed let me know!

### CODE REVIEW

**Comment by contrarybaton60** [comment]
I think that the Notable Features section in the readme is a bit too "literal" in a sense, I think shortening it to only include the important stuff is better like:

- New biomes to explore! (Traverse and Cinderscapes)
- Furniture! (Nemo's Carpentry)
- Ambient visuals and sounds (Falling Leaves, AmbientSounds, etc)
- *optional* Beta 1.7.3 to 1.17 terrain generation (Moderner Beta) 
- Performance optimizations and other QoL changes

**Comment by tristann21** [comment]
> I think that the Notable Features section in the readme is a bit too "literal" in a sense, I think shortening it to only include the important stuff is better like:
> 
>     * New biomes to explore! (Traverse and Cinderscapes)
> 
>     * Furniture, sleeping bags and hammocks! (Nemo's Carpentry, Comforts)
> 
>     * Ambient visuals and sounds (Falling Leaves, AmbientSounds, etc)
> 
>     * _optional_ Beta 1.7.3 to 1.17 terrain generation (Moderner Beta)
> 
>     * Performance optimizations and other QoL changes

That's way better! will do that first thing when I'm on

**Comment by tristann21** [comment]
Dumb GitHub app wouldn't let me title or add a description to the commit, sorry about that!

**Review by contrarybaton60 — APPROVED** [review]

**Comment by contrarybaton60** [comment]
Changed some stuff [c8e96c3](https://github.com/contrarybaton60/Williams-Console/pull/8/commits/c8e96c3917ba2d38f64fac1fc0650afd54c7d521)

**Pull request merged**
